license

diff --git a/piptik b/piptik
--- a/piptik
+++ b/piptik
@@ -1,73 +1,90 @@
-#!/bin/bash
-set -euo pipefail
+# This file is part of piptik
+# 
+# piptik is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published
+# by the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+# 
+# suprps is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-readonly art_file="${1:-}"
-readonly quotes_file="${2:-}"
+source "$(dirname "${BASH_SOURCE[0]}")/global.inc.sh"
+trap '[[ $BASH_COMMAND != "__cmd_comment"* ]] && LAST_CMD="$BASH_COMMAND"' DEBUG
+
+PREFIX="\e[38;5;250m $PIPTIK_CHAR "
+SUFFIX="\e[0m"
+PREFIX_ERR="\e[38;5;167m $PIPTIK_CHAR "
+SUFFIX_ERR="\e[0m"
+
+# Show the message on commands
+__cmd_comment() {
+    
+    local exit_code=$?
+    local cmd="${LAST_CMD%% *}"
+    
+    
+    if (( exit_code != 0 )); then
+        
+        if ! declare -p msgs_error &>/dev/null; then
+            printf "${PREFIX_ERR}%s${SUFFIX_ERR}\n" "I don't know what to say!"
+            return
+        fi
+        
+        local idx=$(( RANDOM % ${#msgs_error[@]} ))
+        printf "${PREFIX_ERR}%s${SUFFIX_ERR}\n" "${msgs_error[$idx]}"
+        return
+    fi
+    
+    local arr_name="msgs_${cmd}"
+    local -n msgs="$arr_name" 2>/dev/null
+    
+    if [[ $(declare -p msgs 2>/dev/null) && ${#msgs[@]} -gt 0 ]]; then
+        local idx=$(( RANDOM % ${#msgs[@]} ))
+        printf "${PREFIX}%s${SUFFIX}\n" "${msgs[$idx]}"
+    fi
+}
+
 
 function check_terminal_size() {
-  local min_cols="${1:-80}"
-  local min_rows="${2:-24}"
-
-  local cols rows
-  cols=$(tput cols)
-  rows=$(tput lines)
-
-  (( cols >= min_cols && rows >= min_rows ))
+    local min_cols="${1:-80}"
+    local min_rows="${2:-24}"
+    
+    local cols rows
+    cols=$(tput cols)
+    rows=$(tput lines)
+    
+    (( cols >= min_cols && rows >= min_rows ))
 }
 
 
-function is_text() {
-  local filename="$1"
-  local file_output
-  file_output=$(file --brief --mime-type "$filename")
-  [[ "$file_output" == text/* ]]
+piptik_prompt() {
+    
+    PROMPT_COMMAND=__cmd_comment
+    PS1="[\u as max@\h \W]\$ "
+
+    if ! declare -p quotes &>/dev/null; then
+        quote="where are the quotes? I'll try to searching... I promise!"
+    else
+        rand_index=$(( RANDOM % ${#quotes[@]} ))
+        quote="${quotes[$rand_index]}"
+    fi
+    
+
+    row=$(printf '%*s'"$quote")
+
+     if check_terminal_size; then
+      echo "$ascii_art"
+    fi
+   
+
+    echo "┐"
+    echo "$PIPTIK_CHAR $row"
+    
 }
 
-# Space is not enough, skipping candy.
-if ! check_terminal_size; then
-  exit
-fi
 
-# Check if required files are provided
-if [[ -z "$art_file" || -z "$quotes_file" ]]; then
-  echo "Usage: $0 <art_file.ascii> <quotes_file.txt>"
-  exit 1
-fi
-
-# Check that files exist and are readable
-if [[ ! -r "$art_file" ]]; then
-  echo "Error: ASCII file '$art_file' does not exist or is not readable."
-  exit 1
-fi
-
-if [[ ! -r "$quotes_file" ]]; then
-  echo "Error: TEXT file '$quotes_file' does not exist or is not readable."
-  exit 1
-fi
-
-# Verify file types
-if ! is_text "$art_file" || ! is_text "$quotes_file"; then
-  echo "Error: '$art_file' is not recognized as a text file."
-  exit 1
-fi
-
-# Load quotes from TXT
-mapfile -t quotes < "$quotes_file"
-if [[ ${#quotes[@]} -eq 0 ]]; then
-  echo "Error: No quotes found in '$quotes_file'."
-  exit 1
-fi
-
-# Select a random quote
-rand_index=$(( RANDOM % ${#quotes[@]} ))
-quote="${quotes[$rand_index]}"
-
-# Optional: define padding
-row=$(printf '%*s'"$quote")
-
-# Read and print ASCII art
-ascii_art=$(<"$art_file")
-echo "$ascii_art"
-echo "┐"
-echo "└┄ $row"
-exit 0
